# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ypxdmOmmSphihicbIMI4px4QVv69AfZ

# **Dictionary to DataFrame**

**Exercise 1**
"""

#Pre-defined lists

names = ['United States', 'Australia','Japan', 'India', 'Russia', 'Morocco','Egypt']
dr = [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

# Import pandas as pd

import pandas as pd

#Create dictionary my_dict with three key: value pairs: my_dict

#key -> country -> names (value)
#key -> 'drive_right -> dr (value)
#key -> cars_per_cap -> cpc (value)

my_dict = {'country': names, 'drive_right': dr, 'cars_per_cap': cpc}

#Build a DataFrame cars from my_dict: cars
#Use pd.DataFrame to turn your dict into a DataFrame called *cars*

cars = pd.DataFrame(my_dict)

#Print cars
print(cars)

"""**Exercise 2**

Inserir o index US, AUS etc ao invés de números 0,1,2,3 para cada estado
"""

#Definition of row_labels

row_labels = ['US','AUS','JPN','IN','RU','MOR','EG']

#Specify row labels of cars
cars.index = row_labels

#Print cars
print(cars)

"""**Exercise 3**

CSV to DataFrame -> Putting data in a dictionary and building a DataFrame is not very efficient, if it have milions of observations. In this case the data is available as files, one of those file types is the CSV(comma-separated values). To import CSV data as Pandas DataFrame, use variable =pd.read_csv()
"""

# This case Pandas already was imported before, but if it's not, it's necessary to import pandas as pd

#Import the cars.csv data: cars

cars = pd.read_csv('cars.csv')  #say if is csv, excel, etc

#Print out cars
print(cars)

"""**Execise 4**

The output of CSV is not entirely what we wanted. Use index_colu insede pd.read_csv() to specify which column in the CVS file should be used as a row label

```

```
"""

#Fix import by including index_col
#first column should actually be used as row labels, set it 0(first column)

cars = pd.read_csv('cars.csv', index_col=0)

#Print out cars
print(cars)